### ISSUE TITLE
Fehlermeldung beim Anlegen neuer Kataloge

### ISSUE THREAD

**Issue by tastethecake** [alnv/catalog-manager#207]
Hallo. 
Seit dem Update heute auf V1.31 kann ich keinen neuen Katalog mehr anlegen, ohne diese Fehlermeldung zu erhalten:

```
Warning: in_array() expects parameter 2 to be array, null given in system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php on line 469

#0 [internal function]: __error(2, 'in_array() expe...', '/Applications/A...', 469, Array)
#1 system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php(469): in_array('cut', NULL)
#2 system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php(73): CatalogManager\CatalogFieldBuilder->getDefaultCatalogFields()
#3 system/modules/catalog-manager/library/alnv/DcBuilder.php(105): CatalogManager\CatalogFieldBuilder->getCatalogFields('', true, NULL)
#4 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(202): CatalogManager\DcBuilder->createDataContainerArray()
#5 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(191): CatalogManager\CatalogManagerInitializer->initializeDcByTablename('', Array, false)
#6 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(33): CatalogManager\CatalogManagerInitializer->initializeDataContainerArrays()
#7 system/initialize.php(243): CatalogManager\CatalogManagerInitializer->initialize()
#8 contao/install.php(16): require('/Applications/A...')
#9 {main}
```

Im Contao-Installer soll ich neue Spalten anlegen:
```
ALTER TABLE `tl_member_group` ADD `` blob NULL;
ALTER TABLE `tl_member_group` ADD `p` blob NULL;
```

Aber wenn ich das mache, erscheint nur noch diese Fehlermeldung:

```
Warning: in_array() expects parameter 2 to be array, null given in system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php on line 469

#0 [internal function]: __error(2, 'in_array() expe...', '/Applications/A...', 469, Array)
#1 system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php(469): in_array('cut', NULL)
#2 system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php(73): CatalogManager\CatalogFieldBuilder->getDefaultCatalogFields()
#3 system/modules/catalog-manager/library/alnv/DcBuilder.php(105): CatalogManager\CatalogFieldBuilder->getCatalogFields('', true, NULL)
#4 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(202): CatalogManager\DcBuilder->createDataContainerArray()
#5 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(191): CatalogManager\CatalogManagerInitializer->initializeDcByTablename('', Array, false)
#6 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(33): CatalogManager\CatalogManagerInitializer->initializeDataContainerArrays()
#7 system/initialize.php(243): CatalogManager\CatalogManagerInitializer->initialize()
#8 contao/install.php(16): require('/Applications/A...')
#9 {main}


Fatal error: Uncaught exception Exception with message Query error: Incorrect column name '' (ALTER TABLE `tl_member_group` ADD `` blob NULL;) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

#0 system/modules/core/library/Contao/Database.php(207): Contao\Database\Statement->query('ALTER TABLE `tl...')
#1 system/modules/core/controllers/BackendInstall.php(608): Contao\Database->query('ALTER TABLE `tl...')
#2 system/modules/core/controllers/BackendInstall.php(181): Contao\BackendInstall->adjustDatabaseTables()
#3 contao/install.php(20): Contao\BackendInstall->run()
#4 {main}
```

Contao läuft noch auf 3.5.40

**Comment by alnv** [comment]
Gefixt in v1.31.8

**Comment by tastethecake** [comment]
Funktioniert leider immer noch nicht. 
Ich kann mich nun weder im Backend einloggen noch das Install-Tool aufrufen. Beide Seiten werden mir zwar angezeigt und ich kann meine Zugangsdaten eingeben, danach lande ich aber auf einer weißen Seite mit Fehlermeldungen. 

Beim Login kommt:

```Warning: in_array() expects parameter 2 to be array, null given in system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php on line 469

#0 [internal function]: __error(2, 'in_array() expe...', '/path/to_...', 469, Array)
#1 system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php(469): in_array('cut', NULL)
#2 system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php(73): CatalogManager\CatalogFieldBuilder->getDefaultCatalogFields()
#3 system/modules/catalog-manager/library/alnv/DcBuilder.php(105): CatalogManager\CatalogFieldBuilder->getCatalogFields('', true, NULL)
#4 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(202): CatalogManager\DcBuilder->createDataContainerArray()
#5 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(191): CatalogManager\CatalogManagerInitializer->initializeDcByTablename('', Array, false)
#6 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(33): CatalogManager\CatalogManagerInitializer->initializeDataContainerArrays()
#7 system/initialize.php(243): CatalogManager\CatalogManagerInitializer->initialize()
#8 contao/index.php(16): require('/path/to_...')
#9 {main}


Warning: session_regenerate_id(): Cannot regenerate session id - headers already sent in system/modules/core/library/Contao/User.php on line 427

#0 [internal function]: __error(2, 'session_regener...', '/path/to_...', 427, Array)
#1 system/modules/core/library/Contao/User.php(427): session_regenerate_id()
#2 system/modules/core/controllers/BackendIndex.php(37): Contao\User->login()
#3 contao/index.php(19): Contao\BackendIndex->__construct()
#4 {main}


Warning: Cannot modify header information - headers already sent by (output started at /path/to/system/helper/functions.php:65) in system/modules/core/library/Contao/System.php on line 574

#0 [internal function]: __error(2, 'Cannot modify h...', '/path/to_...', 574, Array)
#1 system/modules/core/library/Contao/System.php(574): setcookie('BE_USER_AUTH', 'e30aae4d2042d22...', 1565251499, '/', '', false, true)
#2 system/modules/core/library/Contao/User.php(562): Contao\System::setCookie('BE_USER_AUTH', 'e30aae4d2042d22...', 1565251499, '/', NULL, false, true)
#3 system/modules/core/library/Contao/User.php(428): Contao\User->generateSession()
#4 system/modules/core/controllers/BackendIndex.php(37): Contao\User->login()
#5 contao/index.php(19): Contao\BackendIndex->__construct()
#6 {main}```

Beim Installtool kommt diese Meldung:

```Warning: in_array() expects parameter 2 to be array, null given in system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php on line 469

#0 [internal function]: __error(2, 'in_array() expe...', '/path/to_...', 469, Array)
#1 system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php(469): in_array('cut', NULL)
#2 system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php(73): CatalogManager\CatalogFieldBuilder->getDefaultCatalogFields()
#3 system/modules/catalog-manager/library/alnv/DcBuilder.php(105): CatalogManager\CatalogFieldBuilder->getCatalogFields('', true, NULL)
#4 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(202): CatalogManager\DcBuilder->createDataContainerArray()
#5 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(191): CatalogManager\CatalogManagerInitializer->initializeDcByTablename('', Array, false)
#6 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(33): CatalogManager\CatalogManagerInitializer->initializeDataContainerArrays()
#7 system/initialize.php(243): CatalogManager\CatalogManagerInitializer->initialize()
#8 contao/install.php(16): require('/path/to_...')
#9 {main}


Warning: Cannot modify header information - headers already sent by (output started at /path/to/system/helper/functions.php:65) in system/modules/core/library/Contao/System.php on line 574

#0 [internal function]: __error(2, 'Cannot modify h...', '/path/to_...', 574, Array)
#1 system/modules/core/library/Contao/System.php(574): setcookie('TL_INSTALL_AUTH', 'bf44f9502d2d68e...', 1565248411, '/', '', false, true)
#2 system/modules/core/controllers/BackendInstall.php(816): Contao\System::setCookie('TL_INSTALL_AUTH', 'bf44f9502d2d68e...', 1565248411, '/', NULL, false, true)
#3 system/modules/core/controllers/BackendInstall.php(354): Contao\BackendInstall->setAuthCookie()
#4 system/modules/core/controllers/BackendInstall.php(94): Contao\BackendInstall->loginUser()
#5 contao/install.php(20): Contao\BackendInstall->run()
#6 {main}```

**Comment by tastethecake** [comment]
Funktioniert leider immer noch nicht. 
Ich kann mich nun weder im Backend einloggen noch das Install-Tool aufrufen. Beide Seiten werden mir zwar angezeigt und ich kann meine Zugangsdaten eingeben, danach lande ich aber auf einer weißen Seite mit Fehlermeldungen. 

Beim Login kommt:

```Warning: in_array() expects parameter 2 to be array, null given in system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php on line 469

#0 [internal function]: __error(2, 'in_array() expe...', '/path/to_...', 469, Array)
#1 system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php(469): in_array('cut', NULL)
#2 system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php(73): CatalogManager\CatalogFieldBuilder->getDefaultCatalogFields()
#3 system/modules/catalog-manager/library/alnv/DcBuilder.php(105): CatalogManager\CatalogFieldBuilder->getCatalogFields('', true, NULL)
#4 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(202): CatalogManager\DcBuilder->createDataContainerArray()
#5 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(191): CatalogManager\CatalogManagerInitializer->initializeDcByTablename('', Array, false)
#6 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(33): CatalogManager\CatalogManagerInitializer->initializeDataContainerArrays()
#7 system/initialize.php(243): CatalogManager\CatalogManagerInitializer->initialize()
#8 contao/index.php(16): require('/path/to_...')
#9 {main}


Warning: session_regenerate_id(): Cannot regenerate session id - headers already sent in system/modules/core/library/Contao/User.php on line 427

#0 [internal function]: __error(2, 'session_regener...', '/path/to_...', 427, Array)
#1 system/modules/core/library/Contao/User.php(427): session_regenerate_id()
#2 system/modules/core/controllers/BackendIndex.php(37): Contao\User->login()
#3 contao/index.php(19): Contao\BackendIndex->__construct()
#4 {main}


Warning: Cannot modify header information - headers already sent by (output started at /path/to/system/helper/functions.php:65) in system/modules/core/library/Contao/System.php on line 574

#0 [internal function]: __error(2, 'Cannot modify h...', '/path/to_...', 574, Array)
#1 system/modules/core/library/Contao/System.php(574): setcookie('BE_USER_AUTH', 'e30aae4d2042d22...', 1565251499, '/', '', false, true)
#2 system/modules/core/library/Contao/User.php(562): Contao\System::setCookie('BE_USER_AUTH', 'e30aae4d2042d22...', 1565251499, '/', NULL, false, true)
#3 system/modules/core/library/Contao/User.php(428): Contao\User->generateSession()
#4 system/modules/core/controllers/BackendIndex.php(37): Contao\User->login()
#5 contao/index.php(19): Contao\BackendIndex->__construct()
#6 {main}```

Beim Installtool kommt diese Meldung:

```Warning: in_array() expects parameter 2 to be array, null given in system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php on line 469

#0 [internal function]: __error(2, 'in_array() expe...', '/path/to_...', 469, Array)
#1 system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php(469): in_array('cut', NULL)
#2 system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php(73): CatalogManager\CatalogFieldBuilder->getDefaultCatalogFields()
#3 system/modules/catalog-manager/library/alnv/DcBuilder.php(105): CatalogManager\CatalogFieldBuilder->getCatalogFields('', true, NULL)
#4 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(202): CatalogManager\DcBuilder->createDataContainerArray()
#5 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(191): CatalogManager\CatalogManagerInitializer->initializeDcByTablename('', Array, false)
#6 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(33): CatalogManager\CatalogManagerInitializer->initializeDataContainerArrays()
#7 system/initialize.php(243): CatalogManager\CatalogManagerInitializer->initialize()
#8 contao/install.php(16): require('/path/to_...')
#9 {main}


Warning: Cannot modify header information - headers already sent by (output started at /path/to/system/helper/functions.php:65) in system/modules/core/library/Contao/System.php on line 574

#0 [internal function]: __error(2, 'Cannot modify h...', '/path/to_...', 574, Array)
#1 system/modules/core/library/Contao/System.php(574): setcookie('TL_INSTALL_AUTH', 'bf44f9502d2d68e...', 1565248411, '/', '', false, true)
#2 system/modules/core/controllers/BackendInstall.php(816): Contao\System::setCookie('TL_INSTALL_AUTH', 'bf44f9502d2d68e...', 1565248411, '/', NULL, false, true)
#3 system/modules/core/controllers/BackendInstall.php(354): Contao\BackendInstall->setAuthCookie()
#4 system/modules/core/controllers/BackendInstall.php(94): Contao\BackendInstall->loginUser()
#5 contao/install.php(20): Contao\BackendInstall->run()
#6 {main}```

**Comment by alnv** [comment]
Versuch mal bei deiner CM Installation folgendes:
Öffne die "system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php"
und kommentiere die Zeilen von 468 bis 473 aus. 

Du kannst auch mal versuchen die Contao Installation mit einem anderem Browser zu öffnen.

**Comment by tastethecake** [comment]
Das Kommentieren der Zeilen hat kurzfristig geholfen, ich konnte wieder einen neuen Katalog anlegen. 

Nun komme ich aber wieder nicht ins Backend oder Installtool. Es kommen gleich die weißen Seiten mit Fehlermeldungen. 

Fehlermeldung Login:

```
Fatal error: Uncaught exception ParseError with message syntax error, unexpected end of file thrown in system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php on line 649

#0 [internal function]: Contao\ClassLoader::load('CatalogFieldBui...')
#1 [internal function]: spl_autoload_call('CatalogFieldBui...')
#2 system/modules/core/library/Contao/System.php(140): get_class_methods('CatalogFieldBui...')
#3 system/modules/catalog-manager/library/alnv/DcBuilder.php(32): Contao\System->import('CatalogFieldBui...')
#4 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(201): CatalogManager\DcBuilder->__construct(Array, false)
#5 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(191): CatalogManager\CatalogManagerInitializer->initializeDcByTablename('ctlg_art_der_lo...', Array, false)
#6 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(33): CatalogManager\CatalogManagerInitializer->initializeDataContainerArrays()
#7 system/initialize.php(243): CatalogManager\CatalogManagerInitializer->initialize()
#8 contao/index.php(16): require('/path/to_...')
#9 {main}
```

Fehlermeldung Installtool:

```
Fatal error: Uncaught exception ParseError with message syntax error, unexpected end of file thrown in system/modules/catalog-manager/library/alnv/CatalogFieldBuilder.php on line 649

#0 [internal function]: Contao\ClassLoader::load('CatalogFieldBui...')
#1 [internal function]: spl_autoload_call('CatalogFieldBui...')
#2 system/modules/core/library/Contao/System.php(140): get_class_methods('CatalogFieldBui...')
#3 system/modules/catalog-manager/library/alnv/DcBuilder.php(32): Contao\System->import('CatalogFieldBui...')
#4 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(201): CatalogManager\DcBuilder->__construct(Array, false)
#5 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(191): CatalogManager\CatalogManagerInitializer->initializeDcByTablename('ctlg_art_der_lo...', Array, false)
#6 system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php(33): CatalogManager\CatalogManagerInitializer->initializeDataContainerArrays()
#7 system/initialize.php(243): CatalogManager\CatalogManagerInitializer->initialize()
#8 contao/install.php(16): require('/path/to_...')
#9 {main}
```
Passiert in verschiedenen Browsern.

**Comment by tastethecake** [comment]
Wie so oft löst eine komplette Neuinstallation von Contao und allen Extensions das Problem. 
Vielen Dank für die Tipps.
