### ISSUE TITLE
Fehlermeldung Datei-Upload Feld im Frontend

### ISSUE THREAD

**Issue by andre5tz** [alnv/catalog-manager#54]
Hallo Alex,

ich versuche ein Feld Datei-Upload im Frontend in der Detailansicht auszugeben. 
Wenn eine oder auch mehrere Dateien in dem Datensatz vorhanden sind, ist alles OK. 
Erwische ich einen Datensatz, der keine Datei hat, kommt die nachfolgende Fehlermeldung:

Ich frage mich jetzt, ob ich was falsch eingerichtet habe?

```
Fatal error: Uncaught exception Error with message Call to a member function next() on null thrown in composer/vendor/alnv/catalog-manager/library/alnv/DownloadsCreator.php on line 46

#0 composer/vendor/alnv/catalog-manager/library/alnv/Fields/Upload.php(168): CatalogManager\DownloadsCreator->render()
#1 composer/vendor/alnv/catalog-manager/library/alnv/Fields/Upload.php(93): CatalogManager\Upload::renderFiles(Array, Array, Array)
#2 composer/vendor/alnv/catalog-manager/library/alnv/CatalogView.php(882): CatalogManager\Upload::parseValue(Array, Array, Array)
#3 composer/vendor/alnv/catalog-manager/library/alnv/CatalogView.php(483): CatalogManager\CatalogView->parseCatalogValues('', 'sidi_anlagen', Array)
#4 composer/vendor/alnv/catalog-manager/library/alnv/Modules/ModuleUniversalView.php(212): CatalogManager\CatalogView->getCatalogView(Array)
#5 composer/vendor/alnv/catalog-manager/library/alnv/Modules/ModuleUniversalView.php(76): CatalogManager\ModuleUniversalView->determineMasterView()
#6 system/modules/core/modules/Module.php(287): CatalogManager\ModuleUniversalView->compile()
#7 composer/vendor/alnv/catalog-manager/library/alnv/Modules/ModuleUniversalView.php(49): Contao\Module->generate()
#8 system/modules/core/elements/ContentModule.php(59): CatalogManager\ModuleUniversalView->generate()
#9 system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#10 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#11 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#12 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#13 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#14 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#15 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#16 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#17 index.php(20): Contao\FrontendIndex->run()
#18 {main}
```
Eingebunden habe ich die Datei-Uploads im Template so:
```
	<?php if ($this->sidi_anlagen ): ?>
	<div class="ctlg_entity <?= $strName; ?>">
		<span class="ctlg_entity_name">Anlagen</span>
		<div class="ctlg_entity_value"><?= $this->sidi_anlagen ?></div>
	</div>
	<?php endif; ?>
```
Die Einstellungen für das Feld Datei-Upload sehen so aus:
![einstellungen datei-upload - ausschnitt](https://user-images.githubusercontent.com/2168409/28822485-bab5cace-76b9-11e7-9f61-c9046f5fc4e1.jpg)

Wie gesagt, ich habe keine Ahnung, ob ich etwas im Template anpassen muss, oder ob die Funktion quer schießt.

Viele Grüße
André

**Comment by alnv** [comment]
Am Template liegt es nicht. Wenn du den Catalog Manager auf v1.5 aktualisierst, sollte es wieder gehen.

**Comment by andre5tz** [comment]
Danke für die schnelle Rückmeldung. Update auf 1.5.1 gemacht, alles OK :-)

Vielen Dank 👍
